with open('/home/l2euser/canlis-website/redesign/style.css', 'r') as f:
    lines = f.readlines()

# Find the line with ENHANCED TYPOGRAPHY UTILITIES (line 1489 is index 1488)
# We want to insert after line 1487 (the empty line before the comment block)
# Actually we want to insert before line 1488 (the comment block)

insertion_point = 1487  # 0-indexed, so this is line 1488

new_lines = [
    "\n",
    "/* ==========================================\n",
    "   RESPONSIVE — RESERVATIONS PAGE\n",
    "========================================== */\n",
    "@media (max-width: 1024px) {\n",
    "  .reservations-page .page-hero {\n",
    "    padding: clamp(10rem, 14vw, 12rem) 4vw clamp(4rem, 6vw, 5rem);\n",
    "  }\n",
    "\n",
    "  .reservations-page .editorial {\n",
    "    padding: clamp(3rem, 6vw, 5rem) 4vw;\n",
    "  }\n",
    "\n",
    "  .editorial-grid {\n",
    "    grid-template-columns: 1fr;\n",
    "    gap: clamp(2rem, 4vw, 3rem);\n",
    "  }\n",
    "\n",
    "  .editorial-copy {\n",
    "    max-width: 100%;\n",
    "  }\n",
    "}\n",
    "\n",
    "@media (max-width: 760px) {\n",
    "  .reservations-page .page-hero {\n",
    "    padding: clamp(8rem, 12vw, 10rem) 3vw clamp(3rem, 5vw, 4rem);\n",
    "  }\n",
    "\n",
    "  .reservations-page .page-hero h1 {\n",
    "    font-size: clamp(2.5rem, 7vw, 3.5rem);\n",
    "  }\n",
    "\n",
    "  .reservations-page .editorial {\n",
    "    padding: clamp(2.5rem, 5vw, 4rem) 3vw;\n",
    "  }\n",
    "\n",
    "  .editorial-copy {\n",
    "    max-width: 100%;\n",
    "  }\n",
    "\n",
    "  .eyebrow {\n",
    "    font-size: 0.65rem;\n",
    "  }\n",
    "\n",
    "  .editorial p {\n",
    "    font-size: 1rem;\n",
    "    line-height: 1.7;\n",
    "  }\n",
    "\n",
    "  .reservation-cta {\n",
    "    padding: clamp(3rem, 5vw, 4rem) 3vw;\n",
    "  }\n",
    "\n",
    "  .reservation-cta .button {\n",
    "    width: 100%;\n",
    "    max-width: 300px;\n",
    "  }\n",
    "}\n",
    "\n",
    "@media (max-width: 600px) {\n",
    "  .reservations-page .page-hero {\n",
    "    padding: clamp(6rem, 10vw, 8rem) 2vw clamp(2.5rem, 4vw, 3.5rem);\n",
    "  }\n",
    "\n",
    "  .reservations-page .page-hero h1 {\n",
    "    font-size: clamp(2rem, 8vw, 2.8rem);\n",
    "  }\n",
    "\n",
    "  .reservations-page .editorial {\n",
    "    padding: clamp(2rem, 4vw, 3rem) 2vw;\n",
    "  }\n",
    "\n",
    "  .editorial-copy {\n",
    "    max-width: 100%;\n",
    "  }\n",
    "\n",
    "  .eyebrow {\n",
    "    font-size: 0.6rem;\n",
    "    margin-bottom: 1.5rem;\n",
    "  }\n",
    "\n",
    "  .editorial p {\n",
    "    font-size: 0.95rem;\n",
    "    line-height: 1.65;\n",
    "  }\n",
    "\n",
    "  .reservation-cta {\n",
    "    padding: clamp(2.5rem, 4vw, 3.5rem) 2vw;\n",
    "  }\n",
    "}\n",
    "\n",
]

# Insert the new lines
result = lines[:insertion_point] + new_lines + lines[insertion_point:]

with open('/home/l2euser/canlis-website/redesign/style.css', 'w') as f:
    f.writelines(result)

print("Done!")